name: Merge on Team Approval

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  merge_on_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check if all TeamA members approved
        - id: get-members
          uses: garnertb/get-team-members@v1
          with:
            org: garnertb-io
            team_slug: ops
            token: ${{ secrets.GITHUB_TOKEN }}

        - run: "echo ${{ steps.get-members.outputs.members }}"
          shell: bash

      # - name: Enable Merge Button
      #   if: steps.check_approval.outputs.result == 'true'
      #   run: |
      #     # Your command to enable merge button goes here
