name: Merge on Team Approval

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  ORG_NAME: ${{ secrets.ORG_NAME }}
  TEAM_SLUG: ${{ secrets.TEAM_SLUG1 }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  merge_on_approval:
    runs-on: ubuntu-latest

    steps:
        
      - name: Get team members
        run: |
          members=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_SLUG/members)
          echo "::set-output name=members::$(echo $members | jq -r '.[].login')"

      # Add more steps as needed for further processing