name: Merge on Team Approval

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  ORG_NAME: ${{ secrets.ORG_NAME }}
  TEAM_SLUG1: ${{ secrets.TEAM_SLUG1 }}
  TEAM_SLUG2: ${{ secrets.TEAM_SLUG2 }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  merge_on_approval:
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.pr_reviews.outputs.reviews }}

    steps:
        
      - name: Get team1 members
        run: |
          members=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_SLUG1/members)
          echo "::set-output name=members::$(echo $members | jq -r '.[].login')"

      - name: Get team2 members
        run: |
          members=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_SLUG2/members)
          echo "::set-output name=members::$(echo $members | jq -r '.[].login')"

      - name: Get PR Reviews
        id: pr_reviews
        run: |
          {
            echo 'reviews<<EOF'
            curl -sSL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$ORG_NAME/Get-2teams-approval/pulls/1/reviews
            echo EOF
          } >> "$GITHUB_ENV"  

      - name: Extract Approved Users
        id: approved_users
        run: |
          echo "$(echo $reviews | jq -r '.[] | .user.login' )"

