# .github/workflows/display-time.yml
name: Display Time on Push

on: workflow_dispatch

jobs:
  display-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display current time
        run: |
          echo "Current time is $(date)"
